[tool.black]
line-length = 112

[tool.isort]
profile = "black"
line_length = 112

[tool.pylint.main]
max-line-length = 112
disable = [
    "C0114", # missing-module-docstring
    "C0115", # missing-class-docstring
    "C0116", # missing-function-docstring
    "R0903", # too-few-public-methods
    "W0622", # redefined-builtin
    "C0415", # import-outside-toplevel
    "R0401", # cyclic-import
    "C0413", # wrong-import-position
    "W0621", # redefined-outer-name
]

[tool.pytest.ini_options]
pythonpath = "."
filterwarnings = [
    "ignore:tagMap is deprecated. Please use TAG_MAP instead.:DeprecationWarning:pyasn1",
    "ignore:typeMap is deprecated. Please use TYPE_MAP instead.:DeprecationWarning:pyasn1",
]
