name: Python Linting

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies (if any)
      run: pip install -r requirements-dev.txt

    - name: Run isort
      uses: isort/isort-action@v1.1.0
      with:
        # Optional: Specify isort version to use
        # isortVersion: 5.10.1
        # Optional: Specify paths to sort (defaults to . for recursive sorting)
        sortPaths: .
        # Optional: Pass custom configuration options to isort CLI
        configuration: "--check-only --diff" # This will check for unsorted imports and show diff
